-- 課程平台舊表清理:schema.prisma 已不再宣告這些 model(見檔頭註解),
-- 現在正式從資料庫移除。名稱與 zw_ 系列完全不重疊,不影響共用資料庫裡的其他表。
DROP TABLE IF EXISTS "WebhookEvent" CASCADE;
DROP TABLE IF EXISTS "SubscriptionPayment" CASCADE;
DROP TABLE IF EXISTS "Subscription" CASCADE;
DROP TABLE IF EXISTS "VideoAsset" CASCADE;
DROP TABLE IF EXISTS "OrderItem" CASCADE;
DROP TABLE IF EXISTS "Order" CASCADE;
DROP TABLE IF EXISTS "Entitlement" CASCADE;
DROP TABLE IF EXISTS "GiftCode" CASCADE;
DROP TABLE IF EXISTS "Lesson" CASCADE;
DROP TABLE IF EXISTS "Course" CASCADE;
DROP TABLE IF EXISTS "Series" CASCADE;
DROP TABLE IF EXISTS "Session" CASCADE;
DROP TABLE IF EXISTS "Account" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;

-- 開啟 RLS:資料庫連線走 Prisma 直連(table owner),不受影響;
-- 這裡只是擋掉 Supabase 對外網頁 API(PostgREST)在沒有政策時的預設存取。
ALTER TABLE "TarotShare" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TarotUser" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Reading" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Purchase" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DailyDraw" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CardSeen" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "_prisma_migrations" ENABLE ROW LEVEL SECURITY;
